<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="3" ignored="0" total="9" passed="4">
  <reporter-output>
    <line>
      <![CDATA[Inside user reg test]]>
    </line>
    <line>
      <![CDATA[<a href="F:\screenshot\error.jpg" target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href="F:\screenshot\error.jpg" target="_blank"><img src="f:\screenshot\error.jpg" height=200 width=200></a>]]>
    </line>
    <line>
      <![CDATA[<a href="F:\screenshot\error.jpg" target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href="F:\screenshot\error.jpg" target="_blank"><img src="f:\screenshot\error.jpg" height=200 width=200></a>]]>
    </line>
    <line>
      <![CDATA[Inside user reg test]]>
    </line>
    <line>
      <![CDATA[<a href="F:\screenshot\error.jpg" target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href="F:\screenshot\error.jpg" target="_blank"><img src="f:\screenshot\error.jpg" height=200 width=200></a>]]>
    </line>
  </reporter-output>
  <suite name="TestNG Learning" duration-ms="480" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
    <groups>
    </groups>
    <test name="LoginTest" duration-ms="182" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
      <class name="testnglearning.TestCase1">
        <test-method status="PASS" signature="createDbConn()[pri:0, instance:testnglearning.TestCase1@74a10858]" name="createDbConn" is-config="true" duration-ms="27" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDbConn -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:testnglearning.TestCase1@74a10858]" name="launchBrowser" is-config="true" duration-ms="1" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="doUserReg()[pri:1, instance:testnglearning.TestCase1@74a10858]" name="doUserReg" duration-ms="21" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
          <reporter-output>
            <line>
              <![CDATA[Inside user reg test]]>
            </line>
          </reporter-output>
        </test-method> <!-- doUserReg -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:testnglearning.TestCase1@74a10858]" name="closeBrowser" is-config="true" duration-ms="6" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:testnglearning.TestCase1@74a10858]" name="launchBrowser" is-config="true" duration-ms="1" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="doLogin()[pri:2, instance:testnglearning.TestCase1@74a10858]" name="doLogin" duration-ms="9" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:testnglearning.TestCase1@74a10858]" name="closeBrowser" is-config="true" duration-ms="3" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="closeDbConn()[pri:0, instance:testnglearning.TestCase1@74a10858]" name="closeDbConn" is-config="true" duration-ms="1" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDbConn -->
      </class> <!-- testnglearning.TestCase1 -->
    </test> <!-- LoginTest -->
    <test name="Validate Title test" duration-ms="50" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
      <class name="testnglearning.TestCase2">
        <test-method status="FAIL" signature="validateTitles()[pri:0, instance:testnglearning.TestCase2@43a0cee9]" name="validateTitles" duration-ms="39" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Submit button not found !!! did not expect to find [true] but found [false],
Failing the test as the condition is not met]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Submit button not found !!! did not expect to find [true] but found [false],
Failing the test as the condition is not met
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testnglearning.TestCase2.validateTitles(TestCase2.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1175)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href="F:\screenshot\error.jpg" target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href="F:\screenshot\error.jpg" target="_blank"><img src="f:\screenshot\error.jpg" height=200 width=200></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- validateTitles -->
      </class> <!-- testnglearning.TestCase2 -->
    </test> <!-- Validate Title test -->
    <test name="Dependency Test" duration-ms="78" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
      <class name="testnglearning.TestCase3">
        <test-method status="FAIL" signature="doUserReg()[pri:1, instance:testnglearning.TestCase3@710726a3]" name="doUserReg" duration-ms="1" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User not registered successfully]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User not registered successfully
at org.testng.Assert.fail(Assert.java:97)
at testnglearning.TestCase3.doUserReg(TestCase3.java:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1175)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href="F:\screenshot\error.jpg" target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href="F:\screenshot\error.jpg" target="_blank"><img src="f:\screenshot\error.jpg" height=200 width=200></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- doUserReg -->
        <test-method status="SKIP" signature="doLogin()[pri:2, instance:testnglearning.TestCase3@710726a3]" name="doLogin" duration-ms="0" started-at="2020-03-01T11:43:44 IST" depends-on-methods="testnglearning.TestCase3.doUserReg" finished-at="2020-03-01T11:43:44 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestCase3.doLogin()[pri:2, instance:testnglearning.TestCase3@710726a3] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestCase3.doLogin()[pri:2, instance:testnglearning.TestCase3@710726a3] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:99)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1175)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="SKIP" signature="isSkip()[pri:3, instance:testnglearning.TestCase3@710726a3]" name="isSkip" duration-ms="9" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test as the condition is not met]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test as the condition is not met
at testnglearning.TestCase3.isSkip(TestCase3.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1175)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isSkip -->
      </class> <!-- testnglearning.TestCase3 -->
    </test> <!-- Dependency Test -->
  </suite> <!-- TestNG Learning -->
  <suite name="Master Suite" duration-ms="0" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
    <groups>
    </groups>
  </suite> <!-- Master Suite -->
  <suite name="Regression Suite" duration-ms="136" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
    <groups>
    </groups>
    <test name="Regression LoginTest" duration-ms="71" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
      <class name="regression.TestCase1">
        <test-method status="PASS" signature="createDbConn()[pri:0, instance:regression.TestCase1@704921a5]" name="createDbConn" is-config="true" duration-ms="2" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDbConn -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:regression.TestCase1@704921a5]" name="launchBrowser" is-config="true" duration-ms="9" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="doUserReg()[pri:1, instance:regression.TestCase1@704921a5]" name="doUserReg" duration-ms="3" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
          <reporter-output>
            <line>
              <![CDATA[Inside user reg test]]>
            </line>
          </reporter-output>
        </test-method> <!-- doUserReg -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:regression.TestCase1@704921a5]" name="closeBrowser" is-config="true" duration-ms="1" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:regression.TestCase1@704921a5]" name="launchBrowser" is-config="true" duration-ms="1" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="doLogin()[pri:2, instance:regression.TestCase1@704921a5]" name="doLogin" duration-ms="16" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:regression.TestCase1@704921a5]" name="closeBrowser" is-config="true" duration-ms="3" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="closeDbConn()[pri:0, instance:regression.TestCase1@704921a5]" name="closeDbConn" is-config="true" duration-ms="1" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDbConn -->
      </class> <!-- regression.TestCase1 -->
    </test> <!-- Regression LoginTest -->
    <test name="Regression Validate Title test" duration-ms="30" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
      <class name="regression.TestCase2">
        <test-method status="FAIL" signature="validateTitles()[pri:0, instance:regression.TestCase2@31f924f5]" name="validateTitles" duration-ms="18" started-at="2020-03-01T11:43:44 IST" finished-at="2020-03-01T11:43:44 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Submit button not found !!! did not expect to find [true] but found [false],
Failing the test as the condition is not met]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Submit button not found !!! did not expect to find [true] but found [false],
Failing the test as the condition is not met
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at regression.TestCase2.validateTitles(TestCase2.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1175)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href="F:\screenshot\error.jpg" target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href="F:\screenshot\error.jpg" target="_blank"><img src="f:\screenshot\error.jpg" height=200 width=200></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- validateTitles -->
      </class> <!-- regression.TestCase2 -->
    </test> <!-- Regression Validate Title test -->
  </suite> <!-- Regression Suite -->
</testng-results>
